name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest rust stable
        run: rustup update stable && rustup default stable
      - name: Install cargo-expand
        run: cargo install cargo-expand
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose -- --nocapture
